### ISSUE TITLE
Requires permission 'access CiviCRM Civirebux' to get to it in civi menu

### ISSUE THREAD

**Issue by rocxa** [ypranay/org.civicrm.civirebux#1]
People may miss this part of the install/setup as it isn't in the installation/docs I don't think.  It might save a lot of unnecessary questions to add it.

Very nice extension btw :-)

**Comment by jaapjansma** [comment]
@rocxa Do you mean the installation instructions are not up to date? And are missing the part about setting the right permissions?

**Comment by rocxa** [comment]
Yes, I do.

**Comment by ypranay** [comment]
Thanks for bringing it up @rocxa . I have updated the installation instructions in the README file as well as the wiki. 
I hope this resolves this issue, so I am going to go ahead and close this one.
